# Base image
FROM rasa/rasa:main-spacy-en AS base

USER root

RUN apt-get update -qq && \
    apt-get upgrade -qq && \
    apt-get autoremove -y -qq && \
    apt-get autoclean -y -qq

# Build image
FROM base AS build-stage

WORKDIR /build
COPY requirements.txt /build

ENV PATH="/opt/venv/bin:$PATH"

RUN . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip wheel && \
    pip install --no-cache-dir -r requirements.txt

WORKDIR /rasa-server

COPY autocorrect ./autocorrect
RUN python -c "import autocorrect; autocorrect.Speller('en_med')"

COPY rasa ./rasa
WORKDIR /rasa-server/rasa 
RUN rasa telemetry disable && \
    rasa train  

# Runtime image
FROM base AS runtime-stage

COPY --from=build-stage /opt/venv /opt/venv
COPY --from=build-stage /rasa-server /rasa-server

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /rasa-server/rasa 

EXPOSE 5005
CMD [ "rasa", "run", "--enable-api" ] 
