FROM python:3.8-slim

RUN apt-get update -qq && \
    apt-get upgrade -qq && \
    apt-get autoremove -y -qq && \
    apt-get autoclean -y -qq

WORKDIR /rasa-server
VOLUME /tmp

COPY requirements.txt .

ENV PATH="/opt/venv/bin:$PATH"

RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download en_core_web_md

COPY autocorrect ./autocorrect
RUN python -c "import autocorrect; autocorrect.Speller('en_med')"

COPY rasa ./rasa
WORKDIR /rasa-server/rasa 

RUN rasa telemetry disable
RUN rasa train

EXPOSE 5005
CMD [ "rasa", "run", "--enable-api" ] 
