FROM python:3.8-slim

RUN apt-get update -qq && \
    apt-get upgrade -qq && \
    apt-get autoremove -y -qq && \
    apt-get autoclean -y -qq
    
WORKDIR /action-server
VOLUME /tmp

COPY requirements.txt .

ENV PATH="/opt/venv/bin:$PATH"

RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY actions/ ./actions
COPY datasets ./datasets

RUN rasa telemetry disable
CMD [ "rasa", "run", "actions" ] 
