# Base image
FROM rasa/rasa:main AS base

USER root

RUN apt-get update -qq && \
    apt-get upgrade -qq && \
    apt-get autoremove -y -qq && \
    apt-get autoclean -y -qq

# Build image
FROM base AS build-stage

WORKDIR /build
COPY requirements.txt /build

ENV PATH="/opt/venv/bin:$PATH"

RUN . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip wheel && \
    pip install --no-cache-dir -r requirements.txt
  
# Runtime image
FROM base AS runtime-stage

COPY --from=build-stage /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /action-server

COPY actions/ ./actions
COPY datasets ./datasets

RUN rasa telemetry disable
ENTRYPOINT ["rasa"]
CMD [ "run", "actions" ] 
